[project]
name = "landscapes-classification"
version = "0.1.0"
description = "Neural networks based solution for landscapes classification"
authors = [
    {name = "Vladislav Semenov",email = "vliusemenov@edu.hse.ru"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "torch (>=2.9.1,<3.0.0)",
    "torchvision (>=0.24.1,<0.25.0)",
    "torchmetrics (>=1.8.2,<2.0.0)",
    "pytorch-lightning (>=2.6.0,<3.0.0)",
    "mlflow (>=3.8.1,<4.0.0)",
    "hydra-core (>=1.3.2,<2.0.0)",
    "dvc (>=3.65.0,<4.0.0)",
    "dvc-s3 (>=3.2.2,<4.0.0)",
    "gitpython (>=3.1.45,<4.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "fire (>=0.7.1,<0.8.0)"
]

[dependency-groups]
dev = [
    "pre-commit (>=4.5.1,<5.0.0)"
]

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
