# TensorBoard
tensorboard:
  save_dir: "./tensorboard"
  name: "classifier"

mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "landscape-classification"
  run_name: "classifier"
  save_dir: "./mlflow"
